### ISSUE TITLE
Freezes system completely

### ISSUE THREAD

**Issue by Milliw** [albertvaka/yakuake-gnome-extension#1]
Hi!

Many thanks for your extension at first place!
I was using Manjaro KDE for a while and therefore am quite used to the Yakuake terminal.

So now I am on Fedora 35 with GNOME 41 and your extension seems to work fine so far.
But after installing Nvidia drivers and logging into a Wayland session the system freezes as soon as I hit the F12 key. Under X11 session  this is not the case and Yakuake works as intended.

I know that this might not be the correct place to report this but I thought better do it here than nowhere because I don´t have a KDE account and Yakuake bug reports are at bugs.kde.org.

Maybe someone sees this and picks it up or maybe it is even solvable within this git?! =)

**Comment by albertvaka** [comment]
I have no idea about what could be causing this, but let me ask some questions: 
If you configure the extension to use a different key than F12, does it the freeze with the new key?
What's the output of `ps -aux | grep kglobalaccel5`? If `kglobalaccel5` is running, can you try again after killing it?

**Comment by Milliw** [comment]
`ps -aux | grep kglobalaccel5` outputs 
`marco       4968  0.0  0.0 221820  2368 pts/0    S+   12:13   0:00 grep --color=auto kglobalaccel5`

Using a different hotkey doesn´t help. Gnome shell freezes. Can´t even open a terminal with ctrl-alt-f2 or similar.
I´m a Linux noob. I do not understand if that output says kglobalaccel5 is running or not and I don´t know how to kill it either =P

**Comment by albertvaka** [comment]
I have no idea what the issue is :/

Btw: `kglobalaccel5` isn't running. The command you ran shows all the running programs that contain the word "kglobalaccel5" and it only shows one entry: itself (since the command you are running also contains the word 🙂).

**Comment by Milliw** [comment]
Hm. Ok. It´s not too bad for me as I am just using another drop down terminal that works flawlessly.
But though I´m not into terminals and their differences at all I assume that Yakuake has it´s fans and so although it´s no big thing _for me_ switching to another terminal it might be for someone else.

**Comment by Milliw** [comment]
I'm back to Linux and on Nobara 37 (based on Fedora 37) now.
Seems like the issue has been fixed. I had on freeze on fresh install but now it works.

Besides the known issue that the terminal appears in the centre of the screen but that's another issue so I close this one. =)
