### ISSUE TITLE
Nixos port

### ISSUE THREAD

**Issue by SpiderUnderUrBed** [albertvaka/yakuake-gnome-extension#8]
Hi, is there a Nixos port in the works? A nixos port would be really nice. To port it, it would need to be available in the nixos store. 

https://search.nixos.org/packages?channel=24.05&from=0&size=50&sort=relevance&type=packages&query=yakuake-gnome-extension
https://nixos.wiki/wiki/GNOME

Of course, Nixos is kind of a Niche so if you don't feel like implementing Nixos support that is completely fine.

**Comment by albertvaka** [comment]
I don't use Nixos so I can't really test or maintain it there (and I don't understand why it needs a separate store in the fist place). Feel free to upload it to the Nixos store yourself, though.

**Comment by SpiderUnderUrBed** [comment]
Ah ok, fair enough, I will maybe try and make a nixos port at some point then update this issue.

Nixos needs it to be ported to the store because building from source isn't really how it works, packages are supposed to be in /nix/store in a immutable state
